name: Python CI

on:
  push:
    branches: [ functional ]
  pull_request:
    branches: [ functional ]

jobs:
  test:
    runs-on: ubuntu-latest # или windows-latest, macos-latest

    steps:
      - uses: actions/checkout@v3 # Клонирует репозиторий

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9" # Или другая подходящая версия Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Установка зависимостей из requirements.txt

      - name: Run tests with unittest
        run: python -m unittest discover -s tests -p 'test_*.py'
